codebuzz/accounts/urls.py
from django.conf.urls import patterns, url
from accounts.views import *

urlpatterns = patterns('',
    url(r'^login/$', user_login, name="login"),
    url(r'^logout/$', user_logout, name="logout"),
    url(r'^view/(?P<uid>\d+)/$', user_view, name="view"),
)

codebuzz/codebuzz/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include("codesnippet.urls"), name="codebuzz_root"),
    url(r'^codesnippet/', include("codesnippet.urls")),
    url(r'^registration/', include("registration.urls")),
    url(r'^accounts/', include("accounts.urls")),
    # Examples:
    # url(r'^$', 'codebuzz.views.home', name='home'),
    # url(r'^codebuzz/', include('codebuzz.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

codebuzz/codesnippet/urls.py
from django.conf.urls import patterns, include, url
from codesnippet.views import *

urlpatterns = patterns('',
    url(r'^$', index, name="root"),
    url(r'^index/$', index, name="index"),
    url(r'^view/(?P<sid>\d+)/$', view_snippet, name="view"),
    url(r'^random/$', view_random_snippet, name="random"),
    url(r'^browse/$', browser_snippets, name="browse"),
    url(r'^browse/language/(?P<language>[^/]+)/$', browse_language),
    url(r'^browse/category/(?P<category>[^/]+)/$', browse_category),
    url(r'^rating/(?P<sid>\d+)/$', submit_rating, name="rating"),
    url(r'^bookmark/(?P<sid>\d+)/$', bookmark_snippet, name="bookmark"),
    url(r'^comment/(?P<sid>\d+)/$', submit_comment, name="comment"),
    url(r'^search/$', search_snippet, name="search"),
    url(r'^advanced_search/$', advanced_search, name="advanced"),
)

codebuzz/codesnippet/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms

class Category(models.Model):
    """Represents the set of categories to which a snippet belongs."""
    name = models.CharField(max_length=50)
    
    def __unicode__(self):
        return self.name

class Language(models.Model):
    """The languages support by the application."""
    name = models.CharField(max_length=20)
    mode = models.CharField(primary_key=True, max_length=40)
    
    def __unicode__(self):
        return self.name

class Snippet(models.Model):
    """Model to represent a code snippet."""
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category)
    language = models.ForeignKey(Language)
    # Allow NULL user corresponding to Anon.
    user = models.ForeignKey(User, blank=True, null=True,
                             on_delete=models.SET_NULL)
    votes = models.IntegerField(default=0)
    # Number of times viewed (only count registered users)
    hits = models.IntegerField(default=0)
    body = models.TextField()
    
    def __unicode__(self):
        return self.name

    def attrs(self):
        for field in self._meta.fields:
            if field.name != "id":
                yield field.name, getattr(self, field.name)
    
    class Meta:
        ordering = ["name"]

class SnippetRating(models.Model):
    """Records a rating of a snippet by a user."""
    RATINGS = [(x, x) for x in xrange(0, 6)]
    user = models.ForeignKey(User)
    snippet = models.ForeignKey(Snippet)
    rating = models.FloatField(default=0.0)

class Comment(models.Model):
    """User comments on code snippets."""
    # Allow blank foreign keys to allow the setting of them after
    # form submission.
    snippet = models.ForeignKey(Snippet, blank=True, null=True,
                                on_delete=models.SET_NULL)
    user = models.ForeignKey(User, blank=True, null=True,
                             on_delete=models.SET_NULL)
    comment = models.TextField()
    
    def __unicode__(self):
        return self.comment

class Bookmark(models.Model):
    """Represents a user's bookmarking of a code snippet."""
    user = models.ForeignKey(User)
    snippet = models.ForeignKey(Snippet)

    def __unicode__(self):
        return self.snippet.name

codebuzz/codesnippet/forms.py
from django import forms
from codesnippet.models import Category, Comment, Language, Snippet,\
                               SnippetRating

class SnippetForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.order_by('name'))

    class Meta:
        model = Snippet
        fields = ["name", "body", "language", "category"]
        body_attrs = {"id" : "editor", "class" : "CodeMirror"}
        lang_attrs = {"id" : "languages", "onchange" : "selectLang()"}
        widgets = {
            "body" : forms.Textarea(attrs=body_attrs),
            "language" : forms.Select(attrs=lang_attrs),
        }

class SnippetRatingForm(forms.ModelForm):
    rating = forms.ChoiceField(widget=forms.Select(),
                               choices=SnippetRating.RATINGS)
    class Meta:
        model = SnippetRating
        fields = ["rating"]

class SnippetSearchForm(forms.Form):
    name = forms.CharField(max_length=200)
    blank_is_all = "Leave blank to specify all {}."
    language = forms.ModelMultipleChoiceField(queryset=Language.objects.order_by('name'),
                                              required=False,
                             help_text=blank_is_all.format("languages"))
    category = forms.ModelMultipleChoiceField(queryset=Category.objects.order_by('name'),
                                              required=False,
                             help_text=blank_is_all.format("categories"))

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment"]

codebuzz/codesnippet/views.py
from random import randint, seed
try:
	import twitter
	twitterSuccess = True
except:
    print 'Twitter could not be imported'
    twitterSuccess = False
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from django.utils import simplejson
from django import template

from codesnippet.forms import CommentForm, SnippetForm,\
                              SnippetRatingForm, SnippetSearchForm
from codesnippet.models import Bookmark, Category, Comment, Language,\
                               Snippet, SnippetRating
def index(request):
    """Homepage for codesnippet application."""
    context = RequestContext(request)
    if request.method == "POST":
        form = SnippetForm(data = request.POST)
        if form.is_valid():
            snippet = form.save(commit=False)
            if request.user.is_authenticated():
                snippet.user = request.user
            snippet.save()
            if twitterSuccess:
                try:
                    api = twitter.Api(consumer_key='0aIAx6JBFjCRsVo2I6m5VQ',
                                consumer_secret='ezaCJZNLJtTRaIogVvv08u3thnwSTtDMHmRMMs7lyk',
                                access_token_key='1219662349-DJfNG23p2NLME6VAQv02gGNJXLiVQ1r99upKB0k',
                                access_token_secret='P806WM9qbwg81Q1lGsVvRZ1Xl3PACurSmL1BWqCHgg')
                    api.PostUpdate('A new snippet written in ' + 
                                    snippet.language.name + ' called "' + 
                                    snippet.name + '" has just been submitted!')
                except:
                    print 'Twitter posting failed.'
            # Redirect to the view page for the snippet.
            view = "view/{}/".format(snippet.id)
            return HttpResponseRedirect(view)
        else:
            print form.errors
    else:
        form = SnippetForm()
    return render_to_response('index.html', {"form" : form}, context)

def get_rating(request, snippet):
    """Retrieve the rating of the snippet by request user.
    
    Returns None if no such rating exists otherwise returns the rating.
    """
    initial = None
    # Select the initial rating to be the users last submitted
    # rating for the snippet, if there is one.
    if request.user.is_authenticated():
        try:
            initial = SnippetRating.objects.get(snippet=snippet,
                                                user=request.user)
        except ObjectDoesNotExist:
            return None
    if initial is None:
        return None
    return initial.rating

def get_total_rating(snippet):
    """Get the total rating of the snippet."""
    total = 0.0
    try:
        ratings = SnippetRating.objects.filter(snippet=snippet)
        if len(ratings) > 0:
            snippet.votes = len(ratings)
            snippet.save()
            for r in ratings:
                total += r.rating
            total = total / len(ratings)
    except ObjectDoesNotExist:
        pass
    return total

def view_snippet(request, sid):
    """View the snippet with id = sid argument."""
    context = RequestContext(request)
    errors = []
    try:
        snippet = Snippet.objects.get(id=sid)
        snippet.hits += 1
        snippet.save()
        
        # Check to see if this snippet is bookmarked by this user
        bookmarked = False
        if request.user.is_authenticated():
            try:
                Bookmark.objects.get(snippet=snippet, user=request.user)
            except ObjectDoesNotExist:
                pass
            else:
                bookmarked = True
        # Get the comments for this snippet.
        comments = Comment.objects.filter(snippet=snippet)
        
        ratings = SnippetRating.objects.filter(snippet=sid)
        # Set selected rating to the submitted rating for this user
        initial = get_rating(request, snippet)
        if initial is None:
            initial = 0
        rform = SnippetRatingForm(initial={"rating" : int(initial)})
        total_rating = 0.0
        rating_width = 0
        if len(ratings) > 0:
            snippet.votes = len(ratings)
            snippet.save()
            for r in ratings:
                total_rating += r.rating
            total_rating = total_rating / len(ratings)
            # Calculate percentage rating width
            rating_width = (total_rating / 5) * 100
        cform = CommentForm()
        return render_to_response("codesnippet/view_snippet.html",
                              {"snippet" : snippet,
                               "rating" : total_rating,
                               "rating_form" : rform,
                               "bookmarked" : bookmarked,
                               "comments" : comments,
                               "comment_form" : cform,
                               "rating_width" : "{}%".format(int(rating_width)),
                               "errors" : errors},
                              context)
    except ObjectDoesNotExist:
        errors += ["Snippet does not exist"]
        return render_to_response("codesnippet/view_snippet.html",
                                  {"errors" : errors},
                                  context)

@login_required
def submit_rating(request, sid):
    """Submits a user rating of a snippet."""
    context = RequestContext(request)
    if request.method == "POST":
        try:
            urating = int(request.POST["rating"])
        except ValueError:
            pass
        else:
            values = SnippetRating.RATINGS
            if (urating >= values[0][0] and
                    urating <= values[len(values)-1][0]):
                u = request.user
                try:
                    s = Snippet.objects.get(id=sid)
                except ObjectDoesNotExist:
                    pass
                else:
                    try:
                        srating = SnippetRating.objects.get(user=u,
                                                            snippet=s)
                    except ObjectDoesNotExist:
                        srating = SnippetRating(user=u, snippet=s,
                                                rating=urating)
                    else:
                        srating.rating = urating
                    srating.save()
                    total_rating = get_total_rating(s)
                    # Pass new total back to page.
                    obj = simplejson.dumps({"user_rating" : urating,
                                            "total_rating" : "{}".format(total_rating)})
                    return HttpResponse(obj,
                                        content_type="application/json")
@login_required
def submit_comment(request, sid):
    """Submit a rating by a user for a snippet."""
    if request.method == "POST":
        cform = CommentForm(data = request.POST)
        if cform.is_valid():
            comment = cform.save(commit=False)
            comment.user = request.user
            try:
                comment.snippet = Snippet.objects.get(id=sid)
            except ObjectDoesNotExist:
                pass
            else:
                comment.save()
    return HttpResponseRedirect("/codesnippet/view/" + sid)

@login_required
def bookmark_snippet(request, sid):
    """Adds a bookmark to the logged in users account."""
    context = RequestContext(request)
    if request.is_ajax() and request.method == "POST":
        bookmark = request.POST["bookmark"]
        try:
            snippet = Snippet.objects.get(id=sid)
        except ObjectDoesNotExist:
            pass
        else:
            if bookmark == "1":
                try:
                    bk = Bookmark.objects.get(snippet=snippet, user=request.user)
                except ObjectDoesNotExist:
                    bk = Bookmark(snippet=snippet, user=request.user)
                    bk.save()
                return HttpResponse("Snippet has been added to your bookmarks.")
            elif bookmark == "0":
                try:
                    bk = Bookmark.objects.get(snippet=snippet, user=request.user).delete()
                except ObjectDoesNotExist:
                    return HttpResponse("Snippet was not bookmarked.")
                return HttpResponse("Snippet has been removed from your bookmarks.")
    else:
        return HttpResponse("POST FAILED!")

def view_random_snippet(request):
    """Select a random snippet for the database to view."""
    snippets = Snippet.objects.all()
    if len(snippets) == 0:
        return view_snippet(request, -1)
    else:
        index = randint(0, len(snippets)-1)
        snippet = snippets[index]
        return view_snippet(request, snippet.id)

def search_snippet(request):
    """Search results for the query."""
    context = RequestContext(request)
    snippets = None
    query = None
    errors = []
    if request.method == "POST":
        query = request.POST["query"]
        snippets = Snippet.objects.filter(name__contains=query)
    else:
        errors += ["No search term provided."]
    return render_to_response("codesnippet/search_snippet.html",
                                  {"snippets" : snippets,
                                   "query" : query,
                                   "errors" : errors},
                                  context)
def advanced_search(request):
    """Advanced searching of a snippet (by category and language)."""
    context = RequestContext(request)
    snippets = None
    query = None
    errors = []
    if request.method == "POST":
        form = SnippetSearchForm(data = request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            languages = form.cleaned_data["language"]

codebuzz/templates/codesnippet/advanced_search.html
{% extends "base.html" %}
{% block title %}
    CodeBuzz - Advanced Search
{% endblock %}
{% block body %}
    <h3>Advanced Search</h3>
    {% if errors %}
        <h5>Errors:</h5>
        <ul>
            {% for err in errors %}
                <li class="error">{{ err }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if form %}
        <form method="post" action="/codesnippet/advanced_search/">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="submit" value="Search"/>
        </form>
    {% endif %}
{% endblock %}

codebuzz/templates/codesnippet/browse_category.html
{% extends "base.html" %}
{% block title %}CodeBuzz - Browse {{category.capitalize}}{% endblock %}
{% block head_includes %}
	{% load staticfiles %}
{% endblock %}
{% block body %}
<h3>{{category.capitalize}} Snippets</h3>
<h5 class="navigation">Snippets</h5>
{% if snippets %}
    <ol>
        {% for snippet in snippets %}
            <li><a href="/codesnippet/view/{{snippet.id}}">{{snippet.name}} in {{snippet.language}}</a></li>
        {% endfor %}
    </ol>
{% else %}
    <p>No {{category.capitalize}} snippets added yet.</p>
{% endif %}
{% endblock %}

codebuzz/templates/codesnippet/browse_language.html
{% extends "base.html" %}
{% block title %}CodeBuzz - Browse {{language.capitalize}}{% endblock %}
{% block head_includes %}
	{% load staticfiles %}
{% endblock %}
{% block body %}
<h3>{{language.capitalize}} Snippets</h3>
<h5 class="navigation">Snippets</h5>
{% if snippets %}
    <ol>
        {% for snippet in snippets %}
            <li><a href="/codesnippet/view/{{snippet.id}}">{{snippet.name}}</a></li>
        {% endfor %}
    </ol>
{% else %}
    <p>No {{language.capitalize}} snippets added yet.</p>
{% endif %}
{% endblock %}

codebuzz/templates/codesnippet/browse_snippets.html
{% extends "base.html" %}
{% block title %}CodeBuzz - Browse Snippets{% endblock %}
{% block head_includes %}
	{% load staticfiles %}
{% endblock %}
{% block body %}
<h3>Browse Snippets by Language or Category</h3>
<h5 class="navigation">Languages</h5>
{% if languages %}
    <ol>
        {% for language in languages %}
            <li><a href="language/{{language|urlencode}}">{{ language}}</a></li>
        {% endfor %}
    </ol>
{% endif %}
{% if categories %}
    <h5 class="navigation">Categories</h5>
    <ol>
        {% for category in categories %}
            <li><a href="category/{{category.name|urlencode}}">{{category.name}}</a></li>
        {% endfor %}
    </ol>
{% endif %}
{% endblock %}

codebuzz/templates/codesnippet/search_snippet.html
{% extends "base.html" %}
{% block title %}
    CodeBuzz - Search Results
{% endblock %}
{% block head_includes %}
    {% load staticfiles %}
    <script src="{% static "js/lib/codemirror.js" %}"></script>
    <script src="{% static "js"%}/mode/codemirror-compressed.js"></script>
{% endblock %}
{% block body %}
    <h3>Search Results</h3>
    {% if errors %}
        <h5>Errors:</h5>
        <ul>
            {% for err in errors %}
                <li class="error">{{ err }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if snippets %}
        <h5>Snippets matching '{{ query }}':</h5>
        <ul>
            {% for snippet in snippets %}
                <li>
                    <a href="/codesnippet/view/{{ snippet.id }}/">{{ snippet.name }}</a>,
                    Category: {{ snippet.category }}, Language: {{ snippet.language }}
                </li>
            {% endfor %}
        </ul>
    {% elif query %}
        <h5>No snippets matching query '{{ query }}'.</h5>
    {% endif %}
{% endblock %}

codebuzz/templates/codesnippet/view_snippet.html
{% extends "base.html" %}
{% block title %}CodeBuzz - {{ snippet.name.capitalize }} by
    {% if snippet.user %}
        {{ snippet.user }}
    {% else %}
        Anonymous
    {% endif %}
{% endblock %}
{% block head_includes %}
    {% load staticfiles %}
    <script src="{% static "js/lib/codemirror.js" %}"></script>
    <script src="{% static "js"%}/mode/codemirror-compressed.js"></script>
{% endblock %}
{% block body %}
    {% if errors %}
        <h5>Errors:</h5>
        <ul>
            {% for err in errors %}
                <li class="error">{{ err }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if snippet %}
		<h3>{{ snippet.name.capitalize }} by
		{% if snippet.user %}
			<a href="/accounts/view/{{ snippet.user.id }}">{{ snippet.user }}</a>
		{% else %}
			Anonymous
		{% endif %}
		</h3>
        <p>This is {{snippet.name}} by
            {% if snippet.user %}
                <a href="/accounts/view/{{ snippet.user.id }}">{{ snippet.user }}</a>.
            {% else %}
                Anonymous.
            {% endif %}
            It is written in
            <a href="/codesnippet/browse/language/{{ snippet.language|urlencode }}">{{ snippet.language }}</a>
            and is a
            <a href="/codesnippet/browse/category/{{ snippet.category|urlencode }}">{{ snippet.category }}</a> snippet.
            It has been viewed {% ifnotequal snippet.hits 1 %}{{snippet.hits}} times{% else %}once{% endifnotequal %}.</p>
            <p><textarea id="editor">{{ snippet.body }}</textarea></p>
            <!--<label for="rating">Rating:</label>
            <span id="total_rating">{{ rating }}</span>-->
            <div class="empty">
                <div style="width: {{ rating_width }}" class="sventek"></div>
            </div>
            {% if user.is_authenticated %}
                <p>
                    You have given this snippet 
                        <span id="user_rating">
                            {{ rating_form.initial.rating }}
                        </span> Sventeks.
                </p>
            {% else %}
            {% endif %}
            <form id="rating_form" method="post"
                  action="/codesnippet/rating/{{ snippet.id }}/">
                {% csrf_token %}
                {{ rating_form.rating }}
            </form>
        {% if user.is_authenticated %}
                <form action="#" method="post">
                    {% csrf_token %}
                    <p><input type="checkbox" id="bookmark"
                        {% if bookmarked %}
                            checked
                        {% endif %}>Bookmark this snippet.<br/>
                    <span id="sbookmrk">
                        {% if bookmarked %}
                            Snippet is bookmarked.
                        {% endif %}
                    </span></p>
                </form>
        {% endif %}
        {% if not user.is_authenticated %}
            <p>
                <a href="/accounts/login/?next={{ request.path|urlencode }}">Login</a>
                to rate and comment on this snippet.
            </p>
        {% endif %}
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
<a href="https://twitter.com/share" class="twitter-share-button" data-lang="en" data-size="large">Share</a>
        {% if comments %}
            {% for comment in comments %}
                <p class="comment">
                    <a href="/accounts/view/{{ comment.user.id }}">
                        {{ comment.user }} says:
                    </a><br/>
                    {{ comment.comment }}
                </p>
            {% endfor %}
        {% endif %}
        {% if user.is_authenticated %}
                <form id="comment_form" method="post"
                      action="/codesnippet/comment/{{ snippet.id }}/">
                    {% csrf_token %}
                    <p>Comment:</p>
                    {{ comment_form.comment }}<br />
                    <input type="submit" name="submit" value="Post Comment"/>
                </form>
        {% endif %}
        <script>
            $(document).ready(function() {
                var editor = $("#editor")[0];
                var langOpts = $("languages")[0];
                var myCodeMirror = CodeMirror.fromTextArea(editor, {
                    indentUnit: 4,
                    lineNumbers: true,
                    lineWrapping: true,
                    mode: "{{ snippet.language.mode }}",
                    readOnly: true,
                });
                 $("#rating_form").hide();
                // on change event for the rating posting
                $("#id_rating").change(function() {
                    $("#rating_form").submit();
                });
                
                // on click event for adding a bookmark of this snippet
                // to the users account.
                $("#bookmark").click(function() {
                    $.ajax({
                        url: "/codesnippet/bookmark/{{ snippet.id }}/",
                        type: "post",
                        data: {
                            "bookmark" : $("#bookmark").is(":checked") ? "1" : "0",
                            "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']")[0].value
                        },
                        success: function(response) {
                            $("#sbookmrk").html(response);
                        }
                    });
                });
                
                var totalRating = {{ rating }};
                
                function getPercentWidth(rating) {
                    return (rating / 5) * 100;
                }
                
                {% if user.is_authenticated %}
                
                    $(".empty").mousemove(function(e) {
                        var startPos = $(".empty").offset().left;
                        var newWidth = e.pageX - startPos;
                        
                        newWidth = Math.ceil(newWidth/50.0) * 50;
                        if (newWidth > 250) newWidth = 250;
                        
                        var percentWidth = (newWidth / $(".empty").width()) * 100;
                        $(".sventek").width(percentWidth + "%");
                    });
                    
                    $(".empty").click(function(e) {
                        var rating = ($(".sventek").width() / $(".empty").width()) * 5;
                        
                        $.ajax({
                            url: "/codesnippet/rating/{{ snippet.id }}/",
                            type: "post",
                            data: {
                                "rating" : rating,
                                "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']")[0].value
                            },
                            success: function(response) {
                                userRating = response["user_rating"];
                                totalRating = response["total_rating"];
                                $("#total_rating").html(totalRating);
                                $("#user_rating").html(userRating);
                                $(".sventek").width(getPercentWidth(totalRating) + "%");
                            }
                        });
                    });
                    
                    $(".empty").mouseleave(function(e) {
                        $(".sventek").width(getPercentWidth(totalRating) + "%");
                    });
                {% endif %}
                
                /* 
                 * jsrotate:
                 * Rotate Sventeks if we receive the the key sequence
                 * "jsr".
                 */
                
                var down = [];
                var J = 74, R = 82, S = 83;
                $(document).keydown(function(e) {
                    switch (e.keyCode) {
                        case J:
                            if (!down[S] && !down[R]) {
                                down[e.keyCode] = true;
                            }
                            break;
                        case R:
                            if (down[J] && down[S]) {
                                down[e.keyCode] = true;
                            }
                            break;
                        case S:
                            if (down[J]) {
                                down[e.keyCode] = true;
                            }
                            break;
                    }
                }).keyup(function(e) {
                    if (down[J] && down[R] && down[S]) {
                        $(".empty").css("background-image", "none");
                        $(".empty").width("360px");
                        $(".sventek").css("background-image",
                                          "url({{ STATIC_URL }}jsrotate.gif)");
                        down[J] = down[R] = down[S] = false;
                    } else if (e.keyCode != J && e.keyCode != R &&
                               e.keyCode != S) {
                        down[J] = down[R] = down[S] = false;
                    }
                });
            });
        </script>
    {% endif %}
{% endblock %}